// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NIdentity;

#nullable disable

namespace NIdentity.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20221218020026_M202212181100")]
    partial class M202212181100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbCertificate", b =>
                {
                    b.Property<string>("KeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IssuerHash")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("IssuerKeyIdentifier")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("KeyIdentifier")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("RefSHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<int>("RevokeReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RevokeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubjectHash")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("Thumbprint")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("KeySHA1")
                        .HasName("PK_ID");

                    b.HasIndex(new[] { "CreationTime" }, "BY_CTIME");

                    b.HasIndex(new[] { "Issuer" }, "BY_ISSUER");

                    b.HasIndex(new[] { "IssuerHash" }, "BY_ISSUER_HASH");

                    b.HasIndex(new[] { "IssuerKeyIdentifier" }, "BY_ISSUER_KEY");

                    b.HasIndex(new[] { "KeyIdentifier" }, "BY_KEY");

                    b.HasIndex(new[] { "RevokeReason" }, "BY_RCODE");

                    b.HasIndex(new[] { "RevokeTime" }, "BY_RTIME");

                    b.HasIndex(new[] { "SerialNumber" }, "BY_SERIAL_NUMBER");

                    b.HasIndex(new[] { "Subject" }, "BY_SUBJECT");

                    b.HasIndex(new[] { "SubjectHash" }, "BY_SUBJECT_HASH");

                    b.HasIndex(new[] { "ExpirationTime" }, "BY_XTIME");

                    b.HasIndex(new[] { "RefSHA1" }, "UK_RF")
                        .IsUnique();

                    b.HasIndex(new[] { "SubjectHash", "KeyIdentifier" }, "UK_SHK")
                        .IsUnique();

                    b.HasIndex(new[] { "SerialNumber", "IssuerHash" }, "UK_SIH")
                        .IsUnique();

                    b.HasIndex(new[] { "SerialNumber", "IssuerKeyIdentifier" }, "UK_SKI")
                        .IsUnique();

                    b.HasIndex(new[] { "Subject", "KeyIdentifier" }, "UK_SNK")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbCertificateDocument", b =>
                {
                    b.Property<string>("KeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("PathName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Access")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .HasColumnType("LONGTEXT");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<string>("ParentPathName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RefSHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<long>("RevisionNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("KeySHA1", "PathName")
                        .HasName("PK_ID");

                    b.HasIndex(new[] { "Access" }, "BY_ACCESS");

                    b.HasIndex(new[] { "CreationTime" }, "BY_CTIME")
                        .HasDatabaseName("BY_CTIME1");

                    b.HasIndex(new[] { "MimeType" }, "BY_MIME_TYPE");

                    b.HasIndex(new[] { "ParentPathName" }, "BY_PARENT");

                    b.HasIndex(new[] { "LastWriteTime" }, "BY_WCODE");

                    b.HasIndex(new[] { "RefSHA1", "PathName" }, "UK_RF")
                        .IsUnique()
                        .HasDatabaseName("UK_RF1");

                    b.ToTable("CertificateDocuments");
                });

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbCertificatePermission", b =>
                {
                    b.Property<long>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AccessKeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("AuthorityKeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<bool>("CanAlter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanAuthorityInterfere")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanGenerate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanRevoke")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("No");

                    b.HasIndex(new[] { "AccessKeySHA1" }, "BY_ACCSHA1");

                    b.HasIndex(new[] { "AuthorityKeySHA1" }, "BY_ATHSHA1");

                    b.HasIndex(new[] { "KeySHA1" }, "BY_KEYSHA1");

                    b.HasIndex(new[] { "KeySHA1", "AccessKeySHA1" }, "UK_ANTI_DUP")
                        .IsUnique();

                    b.ToTable("CertificatePermissions");
                });

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbCertificateStore", b =>
                {
                    b.Property<string>("KeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("Base64")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("RefSHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("KeySHA1")
                        .HasName("PK_ID");

                    b.HasIndex(new[] { "RefSHA1" }, "UK_RF")
                        .HasDatabaseName("UK_RF2");

                    b.ToTable("CertificateStores");
                });

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbRevokation", b =>
                {
                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorityKeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("IssuerKeyIdentifier")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("RefSHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Number");

                    b.HasIndex(new[] { "AuthorityKeySHA1" }, "BY_ISSUER")
                        .HasDatabaseName("BY_ISSUER1");

                    b.HasIndex(new[] { "Revision" }, "BY_REV");

                    b.HasIndex(new[] { "AuthorityKeySHA1", "RefSHA1" }, "UK_RF")
                        .IsUnique()
                        .HasDatabaseName("UK_RF3");

                    b.ToTable("Revokations");
                });

            modelBuilder.Entity("NIdentity.Core.X509.Server.Repositories.Models.DbRevokationInventory", b =>
                {
                    b.Property<string>("KeySHA1")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeyIdentifier")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<DateTimeOffset>("LastWriteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("KeySHA1");

                    b.ToTable("RevokationInventories");
                });

            modelBuilder.Entity("NIdentity.Endpoints.Server.Repositories.Models.DbEndpoint", b =>
                {
                    b.Property<string>("Inventory")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CautionLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CautionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Inventory", "Address")
                        .HasName("PK_EP");

                    b.HasIndex(new[] { "Address" }, "BY_ADDR");

                    b.HasIndex(new[] { "CautionLevel" }, "BY_CAUTION");

                    b.HasIndex(new[] { "Name" }, "BY_NAME");

                    b.HasIndex(new[] { "Type" }, "BY_TYPE");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("NIdentity.Endpoints.Server.Repositories.Models.DbEndpointInventory", b =>
                {
                    b.Property<string>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("CautionLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CautionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsMetadataPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OwnerKeyIdentifier")
                        .HasMaxLength(41)
                        .HasColumnType("varchar(41)");

                    b.Property<string>("OwnerKeySHA1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Identity");

                    b.HasIndex(new[] { "CautionLevel" }, "BY_CAUTION")
                        .HasDatabaseName("BY_CAUTION1");

                    b.HasIndex(new[] { "Name" }, "BY_NAME")
                        .HasDatabaseName("BY_NAME1");

                    b.HasIndex(new[] { "Owner" }, "BY_OWNER");

                    b.HasIndex(new[] { "OwnerKeyIdentifier" }, "BY_OWNER_KEY_ID");

                    b.HasIndex(new[] { "IsPublic" }, "BY_PUBLIC");

                    b.ToTable("EndpointInventories");
                });

            modelBuilder.Entity("NIdentity.Endpoints.Server.Repositories.Models.DbEndpointNetwork", b =>
                {
                    b.Property<string>("Inventory")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SubnetMask")
                        .HasColumnType("int");

                    b.Property<int>("CautionLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CautionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Inventory", "Address", "SubnetMask")
                        .HasName("PK_EP");

                    b.HasIndex(new[] { "Address" }, "BY_ADDR")
                        .HasDatabaseName("BY_ADDR1");

                    b.HasIndex(new[] { "CautionLevel" }, "BY_CAUTION")
                        .HasDatabaseName("BY_CAUTION2");

                    b.HasIndex(new[] { "Name" }, "BY_NAME")
                        .HasDatabaseName("BY_NAME2");

                    b.HasIndex(new[] { "Type" }, "BY_TYPE")
                        .HasDatabaseName("BY_TYPE1");

                    b.ToTable("EndpointNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
